name: Main
on: [push]
jobs:
  main:
    name: Main
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693
      - name: Run Tests
        run: |
          clojure -X:test:runner
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: |
          clojure -X site.fabricate.prototype.write/publish! :dirs '["./pages"]'
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          #destination_dir: docs
          publish_branch: gh-pages
