name: Main
on: [push]
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - uses: actions/cache@v4.2.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: 1.12.0.1530
      - name: Run Tests
        run: |
          clojure -X:test:runner
