name: Main
on: [push]
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - uses: actions/cache@v4.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.4.1474
      - name: Run Tests
        run: |
          clojure -X:dev:test:runner
