name: Main
on: [push]
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.10.1.693
      - name: Run Tests
        run: |
          clojure -X:test:runner
