name: Publish
# This workflow is triggered on pushes to main.
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.1.693
      - name: Publish
        run: |
          clojure -X site.fabricate.prototype.write/publish :dirs '["./pages"]'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          #destination_dir: docs
          publish_branch: gh-pages
